# Generated by protobuf_init. Do not edit manually.
from .basic_pb2_grpc import BasicServiceServicer
from .basic_pb2_grpc import BasicServiceStub
from .basic_pb2_grpc import add_BasicServiceServicer_to_server
from .basic_pb2_grpc import BasicService
