# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/v1/basic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'basic/v1/basic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from basic.service.v1 import service_pb2 as basic_dot_service_dot_v1_dot_service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62\x61sic/v1/basic.proto\x12\x08\x62\x61sic.v1\x1a\x1e\x62\x61sic/service/v1/service.proto2\x84\x02\n\x0c\x42\x61sicService\x12J\n\x05Hello\x12\x1e.basic.service.v1.HelloRequest\x1a\x1f.basic.service.v1.HelloResponse\"\x00\x12K\n\x04Talk\x12\x1d.basic.service.v1.TalkRequest\x1a\x1e.basic.service.v1.TalkResponse\"\x00(\x01\x30\x01\x12[\n\nBackground\x12#.basic.service.v1.BackgroundRequest\x1a$.basic.service.v1.BackgroundResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic.v1.basic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASICSERVICE']._serialized_start=67
  _globals['_BASICSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
