# Generated by protobuf_init. Do not edit manually.
from .service_pb2 import SomeServiceData
from .service_pb2 import SomeServiceResponse
from .service_pb2 import SomeServiceResponses
from .service_pb2 import HelloRequest
from .service_pb2 import HelloResponse
from .service_pb2 import HelloResponseEvent
from .service_pb2 import TalkRequest
from .service_pb2 import TalkResponse
from .service_pb2 import BackgroundRequest
from .service_pb2 import BackgroundResponse
from .service_pb2 import BackgroundResponseEvent
from .service_pb2 import State
