# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/service/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'basic/service/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloudevents.v1 import cloudevents_pb2 as cloudevents_dot_v1_dot_cloudevents__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62\x61sic/service/v1/service.proto\x12\x10\x62\x61sic.service.v1\x1a cloudevents/v1/cloudevents.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n\x0fSomeServiceData\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n\x04type\x18\x02 \x01(\tR\x04type\"\x8a\x01\n\x13SomeServiceResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n\x07version\x18\x03 \x01(\tR\x07version\x12\x35\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32!.basic.service.v1.SomeServiceDataR\x04\x64\x61ta\"[\n\x14SomeServiceResponses\x12\x43\n\tresponses\x18\x01 \x03(\x0b\x32%.basic.service.v1.SomeServiceResponseR\tresponses\"(\n\x0cHelloRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"L\n\rHelloResponse\x12;\n\x0b\x63loud_event\x18\x01 \x01(\x0b\x32\x1a.cloudevents.v1.CloudEventR\ncloudEvent\"0\n\x12HelloResponseEvent\x12\x1a\n\x08greeting\x18\x01 \x01(\tR\x08greeting\"\'\n\x0bTalkRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"&\n\x0cTalkResponse\x12\x16\n\x06\x61nswer\x18\x01 \x01(\tR\x06\x61nswer\"1\n\x11\x42\x61\x63kgroundRequest\x12\x1c\n\tprocesses\x18\x01 \x01(\x03R\tprocesses\"Q\n\x12\x42\x61\x63kgroundResponse\x12;\n\x0b\x63loud_event\x18\x01 \x01(\x0b\x32\x1a.cloudevents.v1.CloudEventR\ncloudEvent\"\x87\x02\n\x17\x42\x61\x63kgroundResponseEvent\x12-\n\x05state\x18\x01 \x01(\x0e\x32\x17.basic.service.v1.StateR\x05state\x12\x39\n\nstarted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n\x0c\x63ompleted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0b\x63ompletedAt\x12\x43\n\tresponses\x18\x04 \x03(\x0b\x32%.basic.service.v1.SomeServiceResponseR\tresponses*u\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n\rSTATE_PROCESS\x10\x01\x12\x12\n\x0eSTATE_COMPLETE\x10\x02\x12\x0f\n\x0bSTATE_ERROR\x10\x03\x12\x1d\n\x19STATE_COMPLETE_WITH_ERROR\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic.service.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=1065
  _globals['_STATE']._serialized_end=1182
  _globals['_SOMESERVICEDATA']._serialized_start=119
  _globals['_SOMESERVICEDATA']._serialized_end=178
  _globals['_SOMESERVICERESPONSE']._serialized_start=181
  _globals['_SOMESERVICERESPONSE']._serialized_end=319
  _globals['_SOMESERVICERESPONSES']._serialized_start=321
  _globals['_SOMESERVICERESPONSES']._serialized_end=412
  _globals['_HELLOREQUEST']._serialized_start=414
  _globals['_HELLOREQUEST']._serialized_end=454
  _globals['_HELLORESPONSE']._serialized_start=456
  _globals['_HELLORESPONSE']._serialized_end=532
  _globals['_HELLORESPONSEEVENT']._serialized_start=534
  _globals['_HELLORESPONSEEVENT']._serialized_end=582
  _globals['_TALKREQUEST']._serialized_start=584
  _globals['_TALKREQUEST']._serialized_end=623
  _globals['_TALKRESPONSE']._serialized_start=625
  _globals['_TALKRESPONSE']._serialized_end=663
  _globals['_BACKGROUNDREQUEST']._serialized_start=665
  _globals['_BACKGROUNDREQUEST']._serialized_end=714
  _globals['_BACKGROUNDRESPONSE']._serialized_start=716
  _globals['_BACKGROUNDRESPONSE']._serialized_end=797
  _globals['_BACKGROUNDRESPONSEEVENT']._serialized_start=800
  _globals['_BACKGROUNDRESPONSEEVENT']._serialized_end=1063
# @@protoc_insertion_point(module_scope)
